---
-
  hosts: all
  vars_files:
    lab_sudo_pass.yml
  vars:
    ansible_become_pass: "{{ sudo_pass }}"
  tasks: 
    - name: return the ip of hosts
      debug: 
        msg: "{{ ansible_default_ipv4.address }}"
...
