---
- name: list running vms
  hosts: kvm_hosts
  vars_files:
    lab_sudo_pass.yml
  vars:
    ansible_become_pass: "{{ sudo_pass }}"
  tasks: 
    - name: list running vms
      virt: 
        command: list_vms
        state: running
      register: running_vms

    - debug: var=running_vms
